### ISSUE TITLE
Gyproc wall panel in garage needs replacing

### ISSUE THREAD

**Issue by canadaduane** [canadaduane/house#1]
It looks like a previous owner needed access to something inside the wall, but didn't cover up the hole they made. Also, if that "something" is important, maybe we should create a proper subpanel in the wall to provide access.

**Comment by hkdobrev** [comment]
In most cases this would be either a wire or a pipe. If you have a proper drawing of such facilities in your house you could determine whether you would need future access.

**Comment by canadaduane** [comment]
Thanks! I don't think such a drawing exists, but I may end up taking the
whole gyproc wall down, in which case I will create the drawing you speak
of.
