### ISSUE TITLE
Question: Do you 3-D print the designed elements?

### ISSUE THREAD

**Issue by hkdobrev** [canadaduane/house#10]
I see you make 3-D models for some of the elements you use in your house.

Do you make the design first and then find/print the element?

Or you make/buy the element and then design it just to illustrate it better digitally?

I am curious if actually designing and 3-D printing such elements for the household could be useful.

**Comment by canadaduane** [comment]
I design it and then print it. It limits the pieces I can create to
plastic, but I figure other options will become available in time and I can
just focus on the things that are within reach now that will improve life
somehow.

**Comment by crdx** [comment]
Which 3D printer do you have?

**Comment by canadaduane** [comment]
The Ultimaker.

**Comment by igbanam** [comment]
Really cool :+1:
