### ISSUE TITLE
Track lighting in playroom works intermittently

### ISSUE THREAD

**Issue by canadaduane** [canadaduane/house#4]
Sometimes the switch will turn the lights on and off, sometimes it won't.

**Comment by canadaduane** [comment]
The bulbs were the cause.

**Comment by xilience** [comment]
~~How did you manage to include an Issue Tracker in your fork? All other forks of the 'house' project do not have Issue Trackers (including mine). Thanks.~~ Scratch that. Didn't realize it wasn't enabled by default. Thanks!

**Comment by canadaduane** [comment]
Glad you found it!
